### ISSUE TITLE
Week 4 Review Ticket

### ISSUE THREAD

**Issue by GavinYWu** [GavinYWu/Gavin#5]
## Grader: Matthew
CB Create Task completed and documented on GH Pages - Prep to submit to CB on or before May, 2nd. (2 Points - Individual)
- [x] CB Create Task Coding requirements documented: Written portion not completely done correctly -0.5
- [ ] Runtime of Code(with comments) on Replit/Intellij: Create Task does not meet all requirements -0.5

Accounts and Logins Challenges/Hacks ( 3 Points - Pair/Trio)
- [x] Hack#1 Add Phone Number to Sign Up / Authorization screen
- [x] Hack#2 Add logout to CRUD screen: Logout does not work -0.5
- [x] Hack#3 Add login_required to another portion of the project
- [ ] Extra Credit:  A quality design would have login and logout on Navbar with user information.   Be sure to have login protecting something on your site, however, do NOT make entire site under login_required: Not completely finished +0.5

**Comment by SproutingOnion** [comment]
## Total: 4/5
## Grader: Matthew
CB Create Task completed and documented on GH Pages - Prep to submit to CB on or before May, 2nd. (2 Points - Individual)
- [x] CB Create Task Coding requirements documented: Written portion not completely done correctly -0.5
- [ ] Runtime of Code(with comments) on Replit/Intellij: Create Task does not meet all requirements -0.5

Accounts and Logins Challenges/Hacks ( 3 Points - Pair/Trio)
- [x] Hack#1 Add Phone Number to Sign Up / Authorization screen
- [x] Hack#2 Add logout to CRUD screen: Logout does not work -0.5
- [x] Hack#3 Add login_required to another portion of the project
- [ ] Extra Credit:  A quality design would have login and logout on Navbar with user information.   Be sure to have login protecting something on your site, however, do NOT make entire site under login_required: Not completely finished +0.5
